(defun subtail (s n)
  (if (< (length s) n)
    ""
    (subseq s (- (length s) n))))
(defun trimtail (s n)
  (subseq s 0 (- (length s) n)))
(defun p (s)
  (cond ((equal "" s) t)
        ((equal "dream" (subtail s 5)) (p (trimtail s 5)))
        ((equal "dreamer" (subtail s 7)) (p (trimtail s 7)))
        ((equal "erase" (subtail s 5)) (p (trimtail s 5)))
        ((equal "eraser" (subtail s 6)) (p (trimtail s 6)))
        (t nil)))
(format t (if (p (read-line)) "YES~%" "NO~%"))
